export enum AsaasDocumentType {
  IDENTIFICATION = "IDENTIFICATION",
  SOCIAL_CONTRACT = "SOCIAL_CONTRACT",
  ENTREPRENEUR_REQUIREMENT = "ENTREPRENEUR_REQUIREMENT",
  MINUTES_OF_ELECTION = "MINUTES_OF_ELECTION",
  CUSTOM = "CUSTOM",
}