version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  server:
    build: .
    container_name: server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - JWT_SECRET=4x4mpl3-s3cr3t-k3y
      - MONGO_URI=mongodb://mongo:27017/ipe-bank
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - MAIL_USER="naorespondaipebank@gmail.com"
      - MAIL_PASS="ligs xjpr tisb fojg"
