FROM node:18.12-alpine as base
ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm install -g node-gyp typescript pnpm

RUN rm -rf node_modules
RUN pnpm install

EXPOSE 4000

CMD ["pnpm", "server:start:development"]