export enum AccountStatus {
  PENDING = "PENDING",
  WAITING_PAYMENT = "WAITING_PAYMENT",
  WAITING_DOCUMENTS = "WAITING_DOCUMENTS",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  BLOCKED = "BLOCKED",
}
