import { AccountStatusBankAccountInfoApprovedStrategy, AccountStatusBankAccountInfoAwaitingApprovalStrategy, AccountStatusBankAccountInfoPendingStrategy, AccountStatusBankAccountInfoRejectedStrategy, AccountStatusCommercialInfoApprovedStrategy, AccountStatusCommercialInfoAwaitingApprovalStrategy, AccountStatusCommercialInfoPendingStrategy, AccountStatusCommercialInfoRejectedStrategy, AccountStatusDocumentApprovedStrategy, AccountStatusDocumentAwaitingApprovalStrategy,AccountStatusDocumentPendingStrategy, AccountStatusDocumentRejectedStrategy, AccountStatusGeneralApprovalApprovedStrategy,AccountStatusGeneralApprovalAwaitingApprovalStrategy,AccountStatusGeneralApprovalPendingStrategy,AccountStatusGeneralApprovalRejectedStrategy } from "./accountDocumentStrategy";


export const accountDocumentStrategies = {
  AccountStatusBankAccountInfoApprovedStrategy,
  AccountStatusBankAccountInfoAwaitingApprovalStrategy,
  AccountStatusBankAccountInfoPendingStrategy,
  AccountStatusBankAccountInfoRejectedStrategy,
  AccountStatusCommercialInfoApprovedStrategy,
  AccountStatusCommercialInfoAwaitingApprovalStrategy,
  AccountStatusCommercialInfoPendingStrategy,
  AccountStatusCommercialInfoRejectedStrategy,
  AccountStatusDocumentApprovedStrategy,
  AccountStatusDocumentAwaitingApprovalStrategy,
  AccountStatusDocumentPendingStrategy,
  AccountStatusDocumentRejectedStrategy,
  AccountStatusGeneralApprovalApprovedStrategy,
  AccountStatusGeneralApprovalAwaitingApprovalStrategy,
  AccountStatusGeneralApprovalPendingStrategy,
  AccountStatusGeneralApprovalRejectedStrategy,
};