name: Publish Admin to Digital Ocean

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14.0"

      - name: Install PNPM
        uses: pnpm/action-setup@v4
          with:
          version: 9

      - name: Install dependencies with PNPM
        run: pnpm install

      - name: Build Admin
        run: pnpm run admin:build:dev

      # Deploy to Digital Ocean App Platform the dist folder at apps/admin/dist
      - name: Deploy to Digital Ocean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app_name: ipe-admin-staging
          build_command: pnpm run admin:build:dev
          start_command: pnpm run admin:preview:dev
          port: 4173
          env: development
