jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.14"

      - name: Install pnpm
        run: npm install -g pnpm@8.15.4

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Print Node.js and pnpm versions
        run: |
          node -v
          pnpm -v

      - name: Print TypeScript Configuration
        run: cat apps/admin/tsconfig.json

      - name: Compile TypeScript
        run: pnpm exec tsc --project apps/admin/tsconfig.json --noEmit

      - name: Build
        run: pnpm run admin:build:dev

      - name: List Files
        run: ls -la apps/admin/dist

      - name: Print Environment Variables
        run: printenv

      - name: Print Disk Usage
        run: df -h

      - name: Print Memory Usage
        run: free -m

      - name: Print pnpm Dependencies
        run: pnpm list --depth 0

      - name: Print pnpm Workspaces
        run: pnpm workspaces list --json
